version: '3.8'

services:
  atp-gateway:
    build: 
      dockerfile: ./dashboard/Dockerfile
    container_name: atp-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateaway/.env
    volumes:
      - ./gateway:/app
    networks:
      - atp-network
    restart: unless-stopped

  atp-dashboard:
    build: 
      dockerfile: ./dashboard/Dockerfile
    container_name: atp-dashboard
    env_file:
    - ./dashboard/.env
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    networks:
      - atp-network
    depends_on:
      - atp-gateway
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - ATP_GATEWAY_URL=http://atp-gateway:8000
      - WEBHOOK_URL=http://n8n:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - atp-network
    restart: unless-stopped

  uptime-kuma:
      image: louislam/uptime-kuma:1
      container_name: uptime-kuma
      volumes:
        - ./uptime-kuma/data:/app/data
      ports:
        - "3001:3001"
      restart: always

networks:
  atp-network:
    driver: bridge

volumes:
  n8n_data:
